// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD37Qy13z9W4XFkPNeuZjki77jMjUOekcI',
    appId: '1:257280066716:web:de3c2abcbe8e64cbce5959',
    messagingSenderId: '257280066716',
    projectId: 'chat-app-e2faa',
    authDomain: 'chat-app-e2faa.firebaseapp.com',
    storageBucket: 'chat-app-e2faa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwUNmK0HGIgYgT1EIbfGKEkOf4Wl4QB4E',
    appId: '1:257280066716:android:2ae5d9f07d5ff382ce5959',
    messagingSenderId: '257280066716',
    projectId: 'chat-app-e2faa',
    storageBucket: 'chat-app-e2faa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQk_q7L9_IMgvcQLIiTdI1xeIYqw8f3zY',
    appId: '1:257280066716:ios:18ed0687f0db3837ce5959',
    messagingSenderId: '257280066716',
    projectId: 'chat-app-e2faa',
    storageBucket: 'chat-app-e2faa.appspot.com',
    iosClientId: '257280066716-d3apsrvn0aogct2bcosl24uqo148f7kg.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQk_q7L9_IMgvcQLIiTdI1xeIYqw8f3zY',
    appId: '1:257280066716:ios:18ed0687f0db3837ce5959',
    messagingSenderId: '257280066716',
    projectId: 'chat-app-e2faa',
    storageBucket: 'chat-app-e2faa.appspot.com',
    iosClientId: '257280066716-d3apsrvn0aogct2bcosl24uqo148f7kg.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseApp',
  );
}
